#!/usr/bin/env bash
#
# verify-release.sh — post-publication integrity check for a SpaceKai release.
#
# Usage:
#   ./scripts/verify-release.sh <assets-dir> [release-tag]
#
# Checks (exit != 0 when any critical check FAILs):
#   1. Exactly one standalone release APK (SpaceKai-vX.Y.Z.apk).
#   2. The APK name is a release variant (no debug/unsigned/aligned/ABI split/foss).
#   3. SHA256SUMS.txt exists and every listed checksum matches the downloaded file.
#   4. The APK's versionCode beats the highest code ever published (downgrade
#      guard — Android refuses updates with "Application non installée" when
#      the new APK's versionCode is lower than the installed one's).
#   5. Desktop packages present (warn only — an APK-only release is allowed).
#
# Runs in CI after `gh release download`, or locally after downloading a
# release manually. The checksum file is trusted as the source of truth: it is
# generated by the release pipeline with plain basenames, so each `hash  name`
# line must resolve to a file present in the assets directory.

set -euo pipefail

DIR="${1:-assets}"
TAG="${2:-}"

if [ ! -d "$DIR" ]; then
  echo "::error::Assets directory '$DIR' not found." >&2
  exit 1
fi

FAILED=0
warn() { echo "  WARN: $1"; }
pass() { echo "  PASS: $1"; }
fail() { echo "  FAIL: $1"; FAILED=1; }

echo "== SPACEKAI RELEASE VERIFICATION  ${TAG:+tag $TAG}"
echo ""

echo "## Android"
# 1. Exactly one APK — never a split/debug/unsigned set.
APKS=$(find "$DIR" -maxdepth 1 -name '*.apk' 2>/dev/null | sort)
COUNT=$(printf '%s\n' "$APKS" | grep -c '\.apk$' || true)
if [ "$COUNT" -ne 1 ]; then
  fail "expected exactly 1 release APK, found $COUNT"
  APK=""
else
  APK="$APKS"
  pass "single APK: $(basename "$APK")"
fi

# 2. The single APK must be a release variant.
if [ -n "$APK" ]; then
  if echo "$(basename "$APK")" | grep -qE 'debug|unsigned|aligned|arm64|armv7|x86|foss|universal'; then
    fail "APK name looks like a non-release variant: $(basename "$APK")"
  else
    pass "APK name is a release variant"
  fi
  if [ -n "$TAG" ]; then
    if [ "$(basename "$APK")" = "SpaceKai-$TAG.apk" ]; then
      pass "APK name matches release tag: SpaceKai-$TAG.apk"
    else
      fail "APK name does not match tag: expected SpaceKai-$TAG.apk, got $(basename "$APK")"
    fi
  fi
fi

echo ""
echo "## Checksums"
# 3. SHA256SUMS.txt present and every line verified against the downloaded file.
SUMS="$DIR/SHA256SUMS.txt"
if [ ! -f "$SUMS" ]; then
  fail "SHA256SUMS.txt missing"
else
  pass "SHA256SUMS.txt present"
  LINES=0
  while read -r expected file; do
    [ -n "$expected" ] || continue
    # Git Bash's sha256sum marks binary files with a leading '*' — strip it
    # so the filename matches the downloaded asset either way.
    file="${file#\*}"
    LINES=$((LINES + 1))
    if [ ! -f "$DIR/$file" ]; then
      fail "checksum entry '$file' not found among downloaded assets"
      continue
    fi
    actual=$(sha256sum "$DIR/$file" | awk '{print $1}')
    if [ "$actual" = "$expected" ]; then
      pass "sha256 OK for $file"
    else
      fail "sha256 MISMATCH for $file"
    fi
  done < "$SUMS"
  if [ "$LINES" -eq 0 ]; then
    fail "SHA256SUMS.txt is empty"
  fi
fi

echo ""
echo "## Version code (downgrade guard)"
# 4. The published APK must not be a downgrade: its versionCode has to be
# strictly greater than the highest versionCode ever shipped. Real incident
# (2026-08-25): v1.1.6 series shipped code 66, then v1.7.5 shipped 61 — the
# check passed against the previous tag, but Android rejected the install for
# anyone on v1.1.6-3 with "Application non installée". Keep MIN in sync with
# apply-release-pipeline.sh / release-publish.sh and bump it when a release
# ships a higher code. Highest shipped = 72 (v1.8.1; v1.8.0 = 71).
MIN_VERSION_CODE=72
if [ -n "$APK" ] && command -v unzip >/dev/null 2>&1; then
  unzip -p "$APK" AndroidManifest.xml > "$DIR/.manifest.bin" 2>/dev/null || true
  CODE=$(perl -e '
    my $f = shift; open my $fh, "<:raw", $f or die; local $/; my $d = <$fh>; close $fh;
    my $idx = 0;
    while (($idx = index($d, "\x08\x00\x00\x10", $idx)) != -1) {
      my $val = unpack("V", substr($d, $idx+4, 4));
      if ($idx < 20000 && $val > 1 && $val < 500) { print $val; last; }
      $idx += 4;
    }
  ' "$DIR/.manifest.bin" 2>/dev/null || true)
  rm -f "$DIR/.manifest.bin"
  if [[ "$CODE" =~ ^[0-9]+$ ]]; then
    if [ "$CODE" -gt "$MIN_VERSION_CODE" ]; then
      pass "versionCode $CODE > $MIN_VERSION_CODE (beats full history)"
    else
      fail "versionCode $CODE is NOT greater than the highest ever published ($MIN_VERSION_CODE) —"
      fail "Android would refuse this as a downgrade ('Application non installée')"
    fi
  else
    warn "could not read versionCode from AndroidManifest.xml (perl/unzip unavailable?)"
  fi
fi

echo ""
echo "## Desktop"
DESKTOP=$(find "$DIR" -maxdepth 1 \( -name '*.AppImage' -o -name '*.msix' -o -name '*.dmg' -o -name '*windows-installer.zip' \) 2>/dev/null | sort)
if [ -z "$DESKTOP" ]; then
  warn "no desktop packages found (APK-only release)"
else
  for f in $DESKTOP; do
    pass "desktop package: $(basename "$f")"
  done
fi

echo ""
if [ "$FAILED" -eq 1 ]; then
  echo "RESULT: VERIFICATION FAILED"
  exit 1
fi
echo "RESULT: ALL CHECKS PASSED"